version: "3.7"

services:
  opensearch:
    container_name: opensearch
    build:
      context: opensearch/
      args:
        TAG_VERSION: 2.7.0
    volumes:
      - type: bind
        source: ./opensearch/opensearch.yml
        target: /usr/share/opensearch/config/opensearch.yml
      - type: volume
        source: opensearch
        target: /usr/share/opensearch/data
    ports:
      - 9200:9200
    environment:
      TIMEZONE: Europe/Berlin
      TZ: Europe/Berlin
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m

  opensearch-dashboards:
    container_name: opensearch-dashboards
    build:
      context: opensearch-dashboards/
      args:
        TAG_VERSION: 2.7.0
    volumes:
      - type: bind
        source: ./opensearch-dashboards/opensearch_dashboards.yml
        target: /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
        read_only: true
    ports:
      - 5601:5601
    environment:
      TIMEZONE: Europe/Berlin
      TZ: Europe/Berlin
      LS_JAVA_OPTS: "-Xmx1g -Xms256m"
    depends_on:
      - opensearch

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        # TAG_VERSION: "7.16.3"
        TAG_VERSION: "latest"
    volumes:
      - type: bind
        source: ./logstash/pipeline/
        target: /usr/share/logstash/pipeline/
        read_only: true
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/config/pipelines.yml
        target: /usr/share/logstash/config/pipelines.yml
        read_only: true
    ports:
      - 5000:5000
    environment:
      TIMEZONE: Europe/Berlin
      TZ: Europe/Berlin
      LS_JAVA_OPTS: "-Xmx1g -Xms256m"
      LS_OPTS: "--config.reload.automatic"

  filebeat:
    container_name: filebeat
    build:
      context: filebeat/
      args:
        TAG_VERSION: "8.0.1"
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: bind
        source: /c/Users/xxmahamm/Documents/logs
        target: /var/log
    environment:
      TIMEZONE: Europe/Berlin
      TZ: Europe/Berlin
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      HOSTNAME: filebeat

  localstack:
    container_name: "localstack-server"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
      SERVICES: "s3"
      DEFAULT_REGION: "us-west-1"
      AWS_DEFAULT_REGION: "us-west-1"
      HOSTNAME_EXTERNAL: "localstack-server"
      HOSTNAME: "localstack-server"
      USE_SSL: "false"
      DEBUG: "1"
    volumes:  
      - "/var/run/docker.sock:/var/run/docker.sock"

  cli:
    container_name: cli
    image: python:3.7
    command: tail -f /dev/null

volumes:
  opensearch:
