version: '3.2'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.ssl.http.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - /c/Users/xxruslaz/Documents/OpenSearch/opensearch-data:/usr/share/opensearch/data
      - /c/Users/xxruslaz/Documents/OpenSearch/config/config.yaml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
      # - /c/Users/xxruslaz/Documents/OpenSearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - /c/Users/xxruslaz/Documents/OpenSearch/config/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
      - /c/Users/xxruslaz/Documents/OpenSearch/config/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
    ports:
      - 9200:9200
      - 9300:9300 # required for Performance Analyzer
    networks:
      - opensearch-net
    # command: |
    #   bash -c "
    #     rm -rf /usr/share/opensearch/plugins/opensearch-security;
    #     sed -i '/security/d' /usr/share/opensearch/config/opensearch.yml;
    #     /usr/share/opensearch/opensearch-docker-entrypoint.sh
    #   "

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    volumes:
      - /c/Users/xxruslaz/Documents/OpenSearch/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - /c/Users/xxruslaz/Documents/logs:/usr/share/filebeat/logs:ro,Z
      - /c/Users/xxruslaz/Documents/OpenSearch/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z       
    #  - /c/Users/xxruslaz/Documents/OpenSearch/config/securityconfig:/usr/share/opensearch/plugins/opensearch-security/securityconfig
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    # environment:
    #   - input {  start_position => "beginning" } ssl= false tcp { port => 5044} } output { opensearch { hosts => ["http://opensearch:9200"] index => "opensearch-logstash-docker-%{+YYYY.MM.dd}" user => "admin"
    #     password => "admin" ssl => false ssl_certificate_verification => false}}
    depends_on:
      - opensearch
    networks:
      - opensearch-net
    links:
      - opensearch
    # security_opt:
    #   - "no-new-privileges:true"
    # cap_add:
    #   - "SYS_NICE"
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --silent --fail localhost:5044 || exit 1"]
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3
    
  Kibana:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: kibana
    restart: always       
    ports:
      - '5601:5601'
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - SERVER_NAME=kibana.example.org
    depends_on:
      - opensearch  
    networks:
      - opensearch-net

volumes:
  opensearch-data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /opt/data/app/opensearch/storage/opensearch-data

networks:
  opensearch-net: